#!/bin/sh
echo "Content-Type: text/html; charset=utf-8"
echo ""
/www/cgi-bin/wifi_block_all
echo "<html><head><meta charset='utf-8'><meta http-equiv='refresh' content='5;url=/cgi-bin/devices'></head><body>"
echo "<h2>🔒 Все устройства заблокированы</h2><p>Кроме белого списка. WiFi перезагружается...</p></body></html>"
