#!/bin/sh
MAC="$1"
[ -z "$MAC" ] && exit 1
logger -t wifi_schedule "UNBLOCK $MAC"
for iface in $(uci show wireless | grep "=wifi-iface" | cut -d= -f1); do
    uci del_list "${iface}.maclist=${MAC}" 2>/dev/null
done
uci commit wireless
hostapd_cli -i phy0-ap0 deny_acl DEL_MAC "$MAC" 2>/dev/null
hostapd_cli -i phy1-ap0 deny_acl DEL_MAC "$MAC" 2>/dev/null
